name: arpes
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.10

  - astropy>=5.3
  - xarray>=2023.5.0
  - h5py>=3.2.1
  - pyqtgraph>=0.12.4

  - pint>=0.22
  - pandas

  - numpy>=1.21.0,<2.0.0
  - scipy>=1.7.0,<2.0.0
  - lmfit>=1.2.1
  - netCDF4>=1.6.3

  # plotting
  - colorcet
  - matplotlib>=3.5.0
  - bokeh>=3.0.0,<4.0.0
  - ipywidgets>=7.0.1,<8.0.0

  # Misc deps
  - pip

  # pip
  - pip:
      - PySide6>=6.2.2
      - packaging
      - numba>=0.57.1
      - colorama
      - imageio
      - titlecase
      - tqdm
      - rx
      - dill
      - ase>=3.22.1

      # documentation dependencies are basically only these
      - sphinx
      - sphinxcontrib-restbuilder
      - sphinx_rtd_theme
      - nbsphinx
      - sphinx_copybutton
      - -e .
