channels:
  - defaults
dependencies:
  - pip
  - pip:
      - pytest
      - pytest-cov
      - pytest-mock
      - pytest-qt
      - pytest-env
      - pytest-xvfb
      - "https://github.com/arafune/igorpy/tarball/master#egg=igor"
