[tool.black]

line-length = 100

[tool.pydocstyle]
convention = "google"

[tool.coverage.run]
include = ["arpes"]
omit = [
  "tests/*",
  "arpes/plotting/*",
  "arpes/deep_learning/*",
  "arpes/widgets.py",
]

[tool.coverage.report]
exclude_lines = ["raise NotImplementedError", "pragma: no cover"]

[tool.ruff]
target-version = "py310"

line-length = 100
