[project]
name = "arpes"
version = "3.0.1"
description = "PyARPES: An analysis framework for multimodal angle-resolved photoemission spectroscopies"
original_authors = [
  { name = "Conrad Stansbury", email = "chstan@berkeley.edu" },
]
authors = [{ name = "Ryuichi Arafune", email = "ryuichi.arafune@gmail.com" }]
dependencies = [
  "astropy>=5.3",
  "xarray>=2023.5.0",
  "h5py>=3.2.1",
  "pyqtgraph>=0.13.3",
  "pint>=0.22",
  "pandas>=2.0.2",
  "numpy>=1.25.0",
  "scipy>=1.10.1",
  "lmfit>=1.2.1",
  "netCDF4>=1.6.4",
  "colorcet>=3.0.1",
  "matplotlib>=3.7.1",
  "ipywidgets>=8.0.6",
  "scikit-learn>=1.2.2",
  "pip>=23.1.2",
  "numba>=0.57.0",
  "titlecase>=2.4",
  "tqdm>=4.65.0",
  "rx>=3.2.0",
  "dill>=0.3.6",
  "ase>=3.22.1",
  "PyQt5=5.15",
]
readme = "README.md"
requires-python = ">= 3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
  "black>=23.3.0",
  "pytest>=7.3.2",
  "pytest-qt>=4.2.0",
  "colorama>=0.4.6",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.pydocstyle]
convention = "google"

[tool.ruff.pydocstyle]
convention = "google"

[tool.coverge.run]
include = ["arpes"]
omit = [
  "tests/*",
  "arpes/plotting/*",
  "arpes/deep_learning/*",
  "arpes/widgets.py",
]

[tool.coverge.report]
exclude_lines = ["raise NotImplementedError", "pragma: no cover"]

[tool.ruff]
target-version = "py310"

line-length = 100

[tool.black]
line-length = 100
