[project]
name = "arpes"
version = "3.0.1"
description = "PyARPES: An analysis framework for multimodal angle-resolved photoemission spectroscopies"
authors = [
  { name = "Conrad Stansbury", email = "chstan@berkeley.edu" },
  { name = "Ryuichi Arafune", email = "ryuichi.arafune@gmail.com" },
]
dependencies = [
  "astropy>=5.3",
  "xarray>=2023.5.0",
  "lmfit>=1.2.1",
  "matplotlib>=3.7.1",
  "pint>=0.22",
  "h5py>=3.2.1",
  "ase>=3.22.1",
]
readme = "README.rst"
requires-python = ">= 3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
  "colorama>=0.4.6",
  "black>=23.3.0",
  "pytest>=7.3.2",
  "pytest-qt>=4.2.0",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.pydocstyle]
convention = "google"

[tool.ruff.pydocstyle]
convention = "google"

[tool.coverge.run]
include = ["arpes"]
omit = [
  "tests/*",
  "arpes/plotting/*",
  "arpes/deep_learning/*",
  "arpes/widgets.py",
]

[tool.coverge.report]
exclude_lines = ["raise NotImplementedError", "pragma: no cover"]

[tool.ruff]
target-version = "py310"

line-length = 100

[tool.black]
line-length = 100
