[project]
name = "arpes"
version = "3.1.0dd"
description = "PyARPES: An analysis framework for multimodal angle-resolved photoemission spectroscopies"
authors = [
  { name = "Conrad Stansbury", email = "chstan@berkeley.edu" },
  { name = "Ryuichi Arafune", email = "ryuichi.arafune@gmail.com" },
]
dependencies = [
  "astropy>=5.3",
  "xarray>=2023.5.0",
  "lmfit>=1.2.1",
  "matplotlib>=3.7.1",
  "pint>=0.22",
  "h5py>=3.2.1",
  "ase>=3.22.1",
  "PyQt5==5.15.7",
  "dill>=0.3.6",
  "rx>=3.2.0",
  "tqdm>=4.65.0",
  "numba>=0.57.1",
  "netcdf4>=1.6.4",
  "pyqtgraph>=0.12.4",
  "scikit-image>=0.21.0",
]
readme = "README.rst"
requires-python = ">= 3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
  "colorama>=0.4.6",
  "black>=23.3.0",
  "pytest>=7.3.2",
  "pytest-qt>=4.2.0",
  "types-tqdm>=4.65.0.1",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.pydocstyle]
convention = "google"

[tool.ruff.pydocstyle]
convention = "google"

[tool.coverge.run]
include = ["arpes"]
omit = [
  "tests/*",
  "arpes/plotting/*",
  "arpes/deep_learning/*",
  "arpes/widgets.py",
]

[tool.coverge.report]
exclude_lines = ["raise NotImplementedError", "pragma: no cover"]

[tool.ruff]
target-version = "py310"
ignore = [
  "ANN101",
  "N806",   #  non-lowercase-variable-in-function 
  "S101",
  "PD011",  # pandas-use-of-dot-values
  "FBT002", # boolean-default-value-in-function-definition
]
select = ["ALL"]
line-length = 100

exclude = ["scripts", "docs", "conda"]

[tool.black]
line-length = 100
