# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install rye
        uses: eifinger/setup-rye@v4
        id: setup-rye
        with:
          enable-cache: true
          version: "latest"

      - name: Install libhdf5-dev by apt
        run: |
          sudo apt -y update
          sudo apt -y install libhdf5-dev

      - name: Rye activation
        run: |
          rye sync
          rye run pytest tests
