# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install uv
        uses: eifinger/setup-uv@v3

      - name: Set up Python
        run: uv python install 3.11

      - name: Install libhdf5-dev by apt
        run: |
          sudo apt -y update
          sudo apt -y install libhdf5-dev libnetcdf-dev make pandoc

      - name: uv sync
        run: |
          uv sync --all-extras --dev

      - name: test with uv
        run: uv run pytest -vv --color=yes --cov=./  --cov-report=xml

      - name: Build docs
        run: |
          source .venv/bin/activate
          cd docs
          make html

      - uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true # optional (default = false)
          files: ./coverage.xml
          flags: unittests # optional
          name: codecov-umbrella # optional
          token: ${{ secrets.CODECOV_TOKEN }} # required
          verbose: true # optional (default = false)
