name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: "**"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Get pip cache dir
        id: pip-cache
        run: |
          # echo "::set-output name=dir::$(pip cache dir)"
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      - name: Cache PyPI modules
        uses: actions/cache@v3
        env:
          cache-name: cache-pypi
        with:
          path: |
            ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-build-${{ env.cache-name}}-${{ hashFiles('**/environment*.yml') }}

      - name: Source environment, test with pytest and generate coverage
        run: |
          echo "Now running tests"
          python -m pytest -c pytest-config/pytest-coverage-codecov.ini

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          verbose: true
